#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     rightLift,     tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     leftLift,      tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     leftWheel1,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     rightWheel1,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     leftWheel2,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C1_2,     rightWheel2,   tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
 Harvard-Westlake Middle School Robotics Team
 FTC8965
 Tele-Op Code
 Authors: Jonathan Damico, Nomi Ringoach
 Version 1
 Since November 8, 2014
*/

#include "JoystickDriver.c"

task main() //Main task for code
{
	waitForStart();

	while(true)
 	{
		//Get joystick settings and positions
    getJoystickSettings(joystick);

   	//set motor speeds
    //makes sure that we are converting the 127 point signal
    //from the joystick to the 100 point signal used by the robot
    float rightWheels = joystick.joy1_y2;
    float leftWheels = joystick.joy1_y1;

		//Set left wheels
    motor[leftWheel1] = leftWheels;
		motor[leftWheel2] = leftWheels;

    //Set right wheels
		motor[rightWheel1] = rightWheels;
		motor[rightWheel2] = rightWheels;

	}
}
